[serviceweaver]
  name = "server"
  binary = "./server"
  args = ["these", "are", "command", "line", "arguments"]
  env = ["PUT=your", "ENV=vars", "HERE="]
  colocate = [
  ["main/Rock", "main/Paper", "main/Scissors"],
  ["github.com/example/sandy/PeanutButter", "github.com/example/sandy/Jelly"],
]
  rollout = "1m"
