[serviceweaver]
  name = "server"
  binary = "./server"
  args = ["--port", "8080"]
  colocate = [
  ["main/Rock", "main/Paper", "main/Scissors"],
  ["github.com/example/sandy/PeanutButter", "github.com/example/sandy/Jelly"],
]
  rollout = "1m"
[single]
listeners.server = {address = "0.0.0.0:8080"}
