// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package submission

import (
	"codeathon.runwayclub.dev/domain"
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "codeathon.runwayclub.dev/internal/submission/SubmissionService",
		Iface: reflect.TypeOf((*SubmissionService)(nil)).Elem(),
		Impl:  reflect.TypeOf(submissionService{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return submissionService_local_stub{impl: impl.(SubmissionService), tracer: tracer, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "Create", Remote: false, Generated: true}), getByChallengeIdAndUserIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "GetByChallengeIdAndUserId", Remote: false, Generated: true}), getByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "GetById", Remote: false, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "Update", Remote: false, Generated: true}), uploadFilesMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "UploadFiles", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return submissionService_client_stub{stub: stub, createMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "Create", Remote: true, Generated: true}), getByChallengeIdAndUserIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "GetByChallengeIdAndUserId", Remote: true, Generated: true}), getByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "GetById", Remote: true, Generated: true}), updateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "Update", Remote: true, Generated: true}), uploadFilesMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/submission/SubmissionService", Method: "UploadFiles", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return submissionService_server_stub{impl: impl.(SubmissionService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return submissionService_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[SubmissionService] = (*submissionService)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*submissionService)(nil)

// Local stub implementations.

type submissionService_local_stub struct {
	impl                             SubmissionService
	tracer                           trace.Tracer
	createMetrics                    *codegen.MethodMetrics
	getByChallengeIdAndUserIdMetrics *codegen.MethodMetrics
	getByIdMetrics                   *codegen.MethodMetrics
	updateMetrics                    *codegen.MethodMetrics
	uploadFilesMetrics               *codegen.MethodMetrics
}

// Check that submissionService_local_stub implements the SubmissionService interface.
var _ SubmissionService = (*submissionService_local_stub)(nil)

func (s submissionService_local_stub) Create(ctx context.Context, a0 *domain.Submission) (err error) {
	// Update metrics.
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "submission.SubmissionService.Create", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Create(ctx, a0)
}

func (s submissionService_local_stub) GetByChallengeIdAndUserId(ctx context.Context, a0 string, a1 string, a2 *domain.ListOpts) (r0 *domain.ListResult[*domain.Submission], err error) {
	// Update metrics.
	begin := s.getByChallengeIdAndUserIdMetrics.Begin()
	defer func() { s.getByChallengeIdAndUserIdMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "submission.SubmissionService.GetByChallengeIdAndUserId", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetByChallengeIdAndUserId(ctx, a0, a1, a2)
}

func (s submissionService_local_stub) GetById(ctx context.Context, a0 string) (r0 *domain.Submission, err error) {
	// Update metrics.
	begin := s.getByIdMetrics.Begin()
	defer func() { s.getByIdMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "submission.SubmissionService.GetById", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetById(ctx, a0)
}

func (s submissionService_local_stub) Update(ctx context.Context, a0 *domain.Submission) (err error) {
	// Update metrics.
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "submission.SubmissionService.Update", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Update(ctx, a0)
}

func (s submissionService_local_stub) UploadFiles(ctx context.Context, a0 string, a1 []byte, a2 []byte) (err error) {
	// Update metrics.
	begin := s.uploadFilesMetrics.Begin()
	defer func() { s.uploadFilesMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "submission.SubmissionService.UploadFiles", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UploadFiles(ctx, a0, a1, a2)
}

// Client stub implementations.

type submissionService_client_stub struct {
	stub                             codegen.Stub
	createMetrics                    *codegen.MethodMetrics
	getByChallengeIdAndUserIdMetrics *codegen.MethodMetrics
	getByIdMetrics                   *codegen.MethodMetrics
	updateMetrics                    *codegen.MethodMetrics
	uploadFilesMetrics               *codegen.MethodMetrics
}

// Check that submissionService_client_stub implements the SubmissionService interface.
var _ SubmissionService = (*submissionService_client_stub)(nil)

func (s submissionService_client_stub) Create(ctx context.Context, a0 *domain.Submission) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.createMetrics.Begin()
	defer func() { s.createMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "submission.SubmissionService.Create", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_Submission_54a2faef(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s submissionService_client_stub) GetByChallengeIdAndUserId(ctx context.Context, a0 string, a1 string, a2 *domain.ListOpts) (r0 *domain.ListResult[*domain.Submission], err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getByChallengeIdAndUserIdMetrics.Begin()
	defer func() { s.getByChallengeIdAndUserIdMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "submission.SubmissionService.GetByChallengeIdAndUserId", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	enc.String(a0)
	enc.String(a1)
	serviceweaver_enc_ptr_ListOpts_73a4ea72(enc, a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_ListResult_ptr_Submission_6f13012f(dec)
	err = dec.Error()
	return
}

func (s submissionService_client_stub) GetById(ctx context.Context, a0 string) (r0 *domain.Submission, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getByIdMetrics.Begin()
	defer func() { s.getByIdMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "submission.SubmissionService.GetById", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_Submission_54a2faef(dec)
	err = dec.Error()
	return
}

func (s submissionService_client_stub) Update(ctx context.Context, a0 *domain.Submission) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateMetrics.Begin()
	defer func() { s.updateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "submission.SubmissionService.Update", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_Submission_54a2faef(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s submissionService_client_stub) UploadFiles(ctx context.Context, a0 string, a1 []byte, a2 []byte) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.uploadFilesMetrics.Begin()
	defer func() { s.uploadFilesMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "submission.SubmissionService.UploadFiles", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + (len(a1) * 1))
	size += (4 + (len(a2) * 1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	serviceweaver_enc_slice_byte_87461245(enc, a1)
	serviceweaver_enc_slice_byte_87461245(enc, a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.5 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type submissionService_server_stub struct {
	impl    SubmissionService
	addLoad func(key uint64, load float64)
}

// Check that submissionService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*submissionService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s submissionService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Create":
		return s.create
	case "GetByChallengeIdAndUserId":
		return s.getByChallengeIdAndUserId
	case "GetById":
		return s.getById
	case "Update":
		return s.update
	case "UploadFiles":
		return s.uploadFiles
	default:
		return nil
	}
}

func (s submissionService_server_stub) create(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *domain.Submission
	a0 = serviceweaver_dec_ptr_Submission_54a2faef(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Create(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s submissionService_server_stub) getByChallengeIdAndUserId(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()
	var a2 *domain.ListOpts
	a2 = serviceweaver_dec_ptr_ListOpts_73a4ea72(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetByChallengeIdAndUserId(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_ListResult_ptr_Submission_6f13012f(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s submissionService_server_stub) getById(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetById(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_Submission_54a2faef(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s submissionService_server_stub) update(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *domain.Submission
	a0 = serviceweaver_dec_ptr_Submission_54a2faef(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Update(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s submissionService_server_stub) uploadFiles(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 []byte
	a1 = serviceweaver_dec_slice_byte_87461245(dec)
	var a2 []byte
	a2 = serviceweaver_dec_slice_byte_87461245(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.UploadFiles(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type submissionService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that submissionService_reflect_stub implements the SubmissionService interface.
var _ SubmissionService = (*submissionService_reflect_stub)(nil)

func (s submissionService_reflect_stub) Create(ctx context.Context, a0 *domain.Submission) (err error) {
	err = s.caller("Create", ctx, []any{a0}, []any{})
	return
}

func (s submissionService_reflect_stub) GetByChallengeIdAndUserId(ctx context.Context, a0 string, a1 string, a2 *domain.ListOpts) (r0 *domain.ListResult[*domain.Submission], err error) {
	err = s.caller("GetByChallengeIdAndUserId", ctx, []any{a0, a1, a2}, []any{&r0})
	return
}

func (s submissionService_reflect_stub) GetById(ctx context.Context, a0 string) (r0 *domain.Submission, err error) {
	err = s.caller("GetById", ctx, []any{a0}, []any{&r0})
	return
}

func (s submissionService_reflect_stub) Update(ctx context.Context, a0 *domain.Submission) (err error) {
	err = s.caller("Update", ctx, []any{a0}, []any{})
	return
}

func (s submissionService_reflect_stub) UploadFiles(ctx context.Context, a0 string, a1 []byte, a2 []byte) (err error) {
	err = s.caller("UploadFiles", ctx, []any{a0, a1, a2}, []any{})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_Submission_54a2faef(enc *codegen.Encoder, arg *domain.Submission) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_Submission_54a2faef(dec *codegen.Decoder) *domain.Submission {
	if !dec.Bool() {
		return nil
	}
	var res domain.Submission
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_ptr_ListOpts_73a4ea72(enc *codegen.Encoder, arg *domain.ListOpts) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_ListOpts_73a4ea72(dec *codegen.Decoder) *domain.ListOpts {
	if !dec.Bool() {
		return nil
	}
	var res domain.ListOpts
	(&res).WeaverUnmarshal(dec)
	return &res
}

func serviceweaver_enc_ptr_ListResult_ptr_Submission_6f13012f(enc *codegen.Encoder, arg *domain.ListResult[*domain.Submission]) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeBinaryMarshaler(arg)
	}
}

func serviceweaver_dec_ptr_ListResult_ptr_Submission_6f13012f(dec *codegen.Decoder) *domain.ListResult[*domain.Submission] {
	if !dec.Bool() {
		return nil
	}
	var res domain.ListResult[*domain.Submission]
	dec.DecodeBinaryUnmarshaler(&res)
	return &res
}

func serviceweaver_enc_slice_byte_87461245(enc *codegen.Encoder, arg []byte) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.Byte(arg[i])
	}
}

func serviceweaver_dec_slice_byte_87461245(dec *codegen.Decoder) []byte {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]byte, n)
	for i := 0; i < n; i++ {
		res[i] = dec.Byte()
	}
	return res
}
