// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package conf

import (
	"codeathon.runwayclub.dev/domain"
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "codeathon.runwayclub.dev/internal/conf/ConfigService",
		Iface: reflect.TypeOf((*ConfigService)(nil)).Elem(),
		Impl:  reflect.TypeOf(configService{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return configService_local_stub{impl: impl.(ConfigService), tracer: tracer, getConfigMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/conf/ConfigService", Method: "GetConfig", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return configService_client_stub{stub: stub, getConfigMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "codeathon.runwayclub.dev/internal/conf/ConfigService", Method: "GetConfig", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return configService_server_stub{impl: impl.(ConfigService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return configService_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[ConfigService] = (*configService)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*configService)(nil)

// Local stub implementations.

type configService_local_stub struct {
	impl             ConfigService
	tracer           trace.Tracer
	getConfigMetrics *codegen.MethodMetrics
}

// Check that configService_local_stub implements the ConfigService interface.
var _ ConfigService = (*configService_local_stub)(nil)

func (s configService_local_stub) GetConfig(ctx context.Context) (r0 *domain.Config, err error) {
	// Update metrics.
	begin := s.getConfigMetrics.Begin()
	defer func() { s.getConfigMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "conf.ConfigService.GetConfig", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetConfig(ctx)
}

// Client stub implementations.

type configService_client_stub struct {
	stub             codegen.Stub
	getConfigMetrics *codegen.MethodMetrics
}

// Check that configService_client_stub implements the ConfigService interface.
var _ ConfigService = (*configService_client_stub)(nil)

func (s configService_client_stub) GetConfig(ctx context.Context) (r0 *domain.Config, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getConfigMetrics.Begin()
	defer func() { s.getConfigMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "conf.ConfigService.GetConfig", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_Config_4f8f97ae(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.6 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type configService_server_stub struct {
	impl    ConfigService
	addLoad func(key uint64, load float64)
}

// Check that configService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*configService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s configService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetConfig":
		return s.getConfig
	default:
		return nil
	}
}

func (s configService_server_stub) getConfig(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetConfig(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_Config_4f8f97ae(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type configService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that configService_reflect_stub implements the ConfigService interface.
var _ ConfigService = (*configService_reflect_stub)(nil)

func (s configService_reflect_stub) GetConfig(ctx context.Context) (r0 *domain.Config, err error) {
	err = s.caller("GetConfig", ctx, []any{}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_Config_4f8f97ae(enc *codegen.Encoder, arg *domain.Config) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_Config_4f8f97ae(dec *codegen.Decoder) *domain.Config {
	if !dec.Bool() {
		return nil
	}
	var res domain.Config
	(&res).WeaverUnmarshal(dec)
	return &res
}
