name: CI/CD Pipeline for Service Weaver

on:
    workflow_dispatch:
        branches:
            - main
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            -   name: Check out code
                uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.23'

            -   name: Set up Go environment variables
                run: |
                    export GOPATH=$HOME/go
                    export GOMODCACHE=$GOPATH/pkg/mod
                    echo "GOPATH=$GOPATH" >> $GITHUB_ENV
                    echo "GOMODCACHE=$GOMODCACHE" >> $GITHUB_ENV

            -   name: Install Service Weaver CLI
                run: |
                    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest
                    go install github.com/ServiceWeaver/weaver-kube/cmd/weaver-kube@latest
                shell: bash

            -   name: Build Service Weaver application
                run: go build -o server .
                shell: bash

            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Deploy to Kubernetes
                run: |
                    echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
                    weaver kube deploy dep_config.yaml
                    kubectl apply -f /tmp/kube_*.yaml
                env:
                    KUBECONFIG: $HOME/.kube/config
                shell: bash